function des_bits = PDSCH_Symbols2Bits_ldpc(Data_for_Demod, SNR_Mod, ...
    modulation_mode, TransIndex, src_len, current_index) %#ok<INUSD>
%PDSCH_SYMBOLS2BITS_LDPC Soft-demodulate and run the synchronized LDPC chain.

global LDPCCodingRateMatchingParam HARQParam

needs_new_config = ~isfield(LDPCCodingRateMatchingParam, 'decoder_cfg') || ...
    isempty(LDPCCodingRateMatchingParam.decoder_cfg) || TransIndex(1) == 1;
if needs_new_config
    ldpc_config = PDSCH_LDPC_Config();
    sim_param = LDPCCodingRateMatchingParam.SimParam_1;
    sim_param.iterationNumLDPC = ldpc_config.max_iterations;
    LDPCCodingRateMatchingParam.decoder_cfg = ldpc_decoder_config( ...
        1, modulation_mode(1), LDPCCodingRateMatchingParam.C_save(1), ...
        LDPCCodingRateMatchingParam.F_save(1), ldpc_config.RNTI, ...
        ldpc_config.nID, ldpc_config.q, ...
        LDPCCodingRateMatchingParam.len_Er_save, ...
        LDPCCodingRateMatchingParam.len_CB_save(1), {sim_param}, ...
        {LDPCCodingRateMatchingParam.rm_pos_1}, 'src_len', src_len(1), ...
        'HARQMaxTrans', HARQParam.MaxTranx, ...
        'crc_len', 16 + 8 * (src_len(1) > 3824));
    LDPCCodingRateMatchingParam.crc_len = ...
        LDPCCodingRateMatchingParam.decoder_cfg.crc_len(1);
end

llr = newsoft_demodulation36211(Data_for_Demod, ...
    2^modulation_mode(1), SNR_Mod);
decoder_cfg = LDPCCodingRateMatchingParam.decoder_cfg;
decoder_cfg.harq_trans_idx(1) = TransIndex(1);
[des_bits, tb_crc_ok, cb_crc_ok, decoder_cfg, decoded_cb_bits] = ...
    ldpc_llr_to_bits( ...
        llr, decoder_cfg, 1, LDPCCodingRateMatchingParam.C_cut, ldpc_config.LDPC_decoder_cpp_alter);

LDPCCodingRateMatchingParam.decoder_cfg = decoder_cfg;
LDPCCodingRateMatchingParam.last_tb_crc_ok = tb_crc_ok;
LDPCCodingRateMatchingParam.last_cb_crc_ok = cb_crc_ok;
LDPCCodingRateMatchingParam.last_decoded_cb_bits = decoded_cb_bits;
LDPCCodingRateMatchingParam.LLRbuffer_1 = decoder_cfg.LLRbuffer_list{1};
LDPCCodingRateMatchingParam.to_decode_softvalue_1 = ...
    decoder_cfg.to_decode_softvalue_list{1};
end
